apiVersion: apps/v1
kind: Deployment
metadata:
    name: course-svc
    labels:
        app: course-svc
spec:
    replicas: 1
    selector:
        matchLabels:
            app: course-svc
    template:
        metadata:
            labels:
                app: course-svc
        spec:
            containers:
            - name: course-svc
              image: docker.io/<DOCKERHUB_USERNAME>/course-service:latest
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: course-svc
spec:
    selector:
        app: course-svc
    ports:
    - port: 80
      targetPort: 8080

