apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-svc
  namespace: web-apps
  labels:
    app: course-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-svc
  template:
    metadata:
      labels:
        app: course-svc
    spec:
      containers:
        - name: course-svc
          image: 898919247265.dkr.ecr.us-east-2.amazonaws.com/course-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: course-svc
  namespace: web-apps
spec:
  type: ClusterIP
  selector:
    app: course-svc
  ports:
    - port: 80
      targetPort: 8080
