apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-svc
  namespace: web-apps
  labels:
    app: enrollment-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-svc
  template:
    metadata:
      labels:
        app: enrollment-svc
    spec:
      containers:
      - name: enrollment-svc
        image: 898919247265.dkr.ecr.us-east-2.amazonaws.com/enrollment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-svc
  namespace: web-apps
spec:
  type: ClusterIP
  selector:
    app: enrollment-svc
  ports:
  - port: 80
    targetPort: 8080

