apiVersion: apps/v1
kind: Deployment
metadata:
    name: swagger-ui
    labels:
        app: swagger-ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: swagger-ui
    template:
        metadata:
            labels:
                app: swagger-ui
        spec:
            containers:
            - name: swagger-ui
              image: docker.io/<DOCKERHUB_USERNAME>/swagger-ui:latest
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: swagger-ui
spec:
    type: LoadBalancer
    selector:
        app: swagger-ui
    ports:
    - port: 80
      targetPort: 8080

