apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: web-apps
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: 898919247265.dkr.ecr.us-east-2.amazonaws.com/swagger-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: web-apps
spec:
  type: LoadBalancer
  selector:
    app: swagger-ui
  ports:
  - port: 80
    targetPort: 8080

