apiVersion: apps/v1
kind: Deployment
metadata:
    name: notification-svc
    labels:
        app: notification-svc
spec:
    replicas: 1
    selector:
        matchLabels:
            app: notification-svc
    template:
        metadata:
            labels:
                app: notification-svc
        spec:
            containers:
            - name: notification-svc
              image: docker.io/<DOCKERHUB_USERNAME>/notification-service:latest
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: notification-svc
spec:
    selector:
        app: notification-svc
    ports:
    - port: 80
      targetPort: 8080

